"""Augment mock_data.json with additional Miami incidents for testing."""

from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path


DATA_PATH = Path(__file__).resolve().parents[1] / "data" / "mock_data.json"


def _timestamp(day: int, hour: int, minute: int) -> str:
    dt = datetime(2024, 4, day, hour, minute, tzinfo=timezone.utc)
    return dt.isoformat().replace("+00:00", "Z")


NEW_INCIDENTS = [
    # Brickell / R1 corridor
    {
        "city_key": "MIA",
        "incident_code": "MOCK240101",
        "incident_date": _timestamp(6, 22, 30),
        "incident_offense": "Robbery",
        "incident_offense_code": "120",
        "incident_offense_description": "Robbery - Street",
        "incident_offense_detail_description": "Armed robbery reported near Brickell Ave & SE 8th St",
        "incident_offense_crime_against": "Person",
        "incident_offense_action": "C",
        "incident_source_original_type": "ROBBERY - STREET",
        "incident_source_name": "Mock_Data",
        "incident_latitude": 25.7689,
        "incident_longitude": -80.1931,
        "incident_address": "900 Brickell Ave",
    },
    {
        "city_key": "MIA",
        "incident_code": "MOCK240102",
        "incident_date": _timestamp(7, 0, 15),
        "incident_offense": "Aggravated Assault",
        "incident_offense_code": "13A",
        "incident_offense_description": "Aggravated Assault",
        "incident_offense_detail_description": "Fight with weapon near S Miami Ave & SE 12th St",
        "incident_offense_crime_against": "Person",
        "incident_offense_action": "C",
        "incident_source_original_type": "ASSAULT - AGGRAVATED",
        "incident_source_name": "Mock_Data",
        "incident_latitude": 25.7662,
        "incident_longitude": -80.1938,
        "incident_address": "1200 S Miami Ave",
    },
    {
        "city_key": "MIA",
        "incident_code": "MOCK240103",
        "incident_date": _timestamp(8, 1, 45),
        "incident_offense": "Motor Vehicle Theft",
        "incident_offense_code": "240",
        "incident_offense_description": "Motor Vehicle Theft",
        "incident_offense_detail_description": "Parking garage vehicle theft near Brickell Key Dr",
        "incident_offense_crime_against": "Property",
        "incident_offense_action": "C",
        "incident_source_original_type": "MOTOR VEHICLE THEFT - PARKING GARAGE",
        "incident_source_name": "Mock_Data",
        "incident_latitude": 25.7648,
        "incident_longitude": -80.1879,
        "incident_address": "701 Brickell Key Dr",
    },
    # Wynwood / R2 loop
    {
        "city_key": "MIA",
        "incident_code": "MOCK240201",
        "incident_date": _timestamp(6, 23, 50),
        "incident_offense": "Burglary",
        "incident_offense_code": "220",
        "incident_offense_description": "Commercial Burglary",
        "incident_offense_detail_description": "Business break-in along NW 2nd Ave & 25th St",
        "incident_offense_crime_against": "Property",
        "incident_offense_action": "C",
        "incident_source_original_type": "BURGLARY - COMMERCIAL",
        "incident_source_name": "Mock_Data",
        "incident_latitude": 25.8024,
        "incident_longitude": -80.1994,
        "incident_address": "2501 NW 2nd Ave",
    },
    {
        "city_key": "MIA",
        "incident_code": "MOCK240202",
        "incident_date": _timestamp(7, 21, 5),
        "incident_offense": "Drug/Narcotic Violations",
        "incident_offense_code": "35A",
        "incident_offense_description": "Drug Possession",
        "incident_offense_detail_description": "Narcotics arrest near NW 23rd St & NW 1st Ct",
        "incident_offense_crime_against": "Society",
        "incident_offense_action": "A",
        "incident_source_original_type": "NARCOTICS - POSSESSION",
        "incident_source_name": "Mock_Data",
        "incident_latitude": 25.8009,
        "incident_longitude": -80.1972,
        "incident_address": "NW 23rd St & NW 1st Ct",
    },
    {
        "city_key": "MIA",
        "incident_code": "MOCK240203",
        "incident_date": _timestamp(8, 2, 25),
        "incident_offense": "Robbery",
        "incident_offense_code": "120",
        "incident_offense_description": "Robbery - Carjacking",
        "incident_offense_detail_description": "Attempted carjacking near NW 1st Ave & NW 26th St",
        "incident_offense_crime_against": "Person",
        "incident_offense_action": "C",
        "incident_source_original_type": "ROBBERY - CARJACKING",
        "incident_source_name": "Mock_Data",
        "incident_latitude": 25.8036,
        "incident_longitude": -80.1955,
        "incident_address": "NW 1st Ave & NW 26th St",
    },
    # South Beach / R3
    {
        "city_key": "MIA",
        "incident_code": "MOCK240301",
        "incident_date": _timestamp(6, 20, 40),
        "incident_offense": "Aggravated Assault",
        "incident_offense_code": "13A",
        "incident_offense_description": "Aggravated Assault",
        "incident_offense_detail_description": "Bar disturbance near Collins Ave & 15th St",
        "incident_offense_crime_against": "Person",
        "incident_offense_action": "C",
        "incident_source_original_type": "ASSAULT - AGGRAVATED",
        "incident_source_name": "Mock_Data",
        "incident_latitude": 25.7904,
        "incident_longitude": -80.1294,
        "incident_address": "1501 Collins Ave",
    },
    {
        "city_key": "MIA",
        "incident_code": "MOCK240302",
        "incident_date": _timestamp(7, 3, 20),
        "incident_offense": "Theft from Vehicle",
        "incident_offense_code": "23F",
        "incident_offense_description": "Theft from Vehicle",
        "incident_offense_detail_description": "Window smash near Washington Ave & 13th St",
        "incident_offense_crime_against": "Property",
        "incident_offense_action": "C",
        "incident_source_original_type": "THEFT - FROM MOTOR VEHICLE",
        "incident_source_name": "Mock_Data",
        "incident_latitude": 25.7867,
        "incident_longitude": -80.1328,
        "incident_address": "1335 Washington Ave",
    },
    {
        "city_key": "MIA",
        "incident_code": "MOCK240303",
        "incident_date": _timestamp(8, 4, 55),
        "incident_offense": "Robbery",
        "incident_offense_code": "120",
        "incident_offense_description": "Robbery",
        "incident_offense_detail_description": "Cell phone theft near Ocean Dr & 11th St",
        "incident_offense_crime_against": "Person",
        "incident_offense_action": "C",
        "incident_source_original_type": "ROBBERY - STRONG ARM",
        "incident_source_name": "Mock_Data",
        "incident_latitude": 25.7807,
        "incident_longitude": -80.1319,
        "incident_address": "1050 Ocean Dr",
    },
    # Coconut Grove / R4
    {
        "city_key": "MIA",
        "incident_code": "MOCK240401",
        "incident_date": _timestamp(6, 19, 15),
        "incident_offense": "Theft",
        "incident_offense_code": "23H",
        "incident_offense_description": "Other Theft",
        "incident_offense_detail_description": "Bike theft near Bayshore Dr & Pan American Dr",
        "incident_offense_crime_against": "Property",
        "incident_offense_action": "C",
        "incident_source_original_type": "THEFT - BICYCLE",
        "incident_source_name": "Mock_Data",
        "incident_latitude": 25.7272,
        "incident_longitude": -80.2359,
        "incident_address": "2699 Bayshore Dr",
    },
    {
        "city_key": "MIA",
        "incident_code": "MOCK240402",
        "incident_date": _timestamp(7, 21, 45),
        "incident_offense": "Aggravated Assault",
        "incident_offense_code": "13A",
        "incident_offense_description": "Aggravated Assault",
        "incident_offense_detail_description": "Road rage incident near S Bayshore Dr & Aviation Ave",
        "incident_offense_crime_against": "Person",
        "incident_offense_action": "C",
        "incident_source_original_type": "ASSAULT - AGGRAVATED",
        "incident_source_name": "Mock_Data",
        "incident_latitude": 25.7286,
        "incident_longitude": -80.2343,
        "incident_address": "Aviation Ave & S Bayshore Dr",
    },
    {
        "city_key": "MIA",
        "incident_code": "MOCK240403",
        "incident_date": _timestamp(8, 0, 5),
        "incident_offense": "Burglary",
        "incident_offense_code": "220",
        "incident_offense_description": "Residential Burglary",
        "incident_offense_detail_description": "Apartment burglary near Oak Ave & Hibiscus St",
        "incident_offense_crime_against": "Property",
        "incident_offense_action": "C",
        "incident_source_original_type": "BURGLARY - RESIDENTIAL",
        "incident_source_name": "Mock_Data",
        "incident_latitude": 25.7289,
        "incident_longitude": -80.2387,
        "incident_address": "3200 Oak Ave",
    },
    # Little Havana / R5
    {
        "city_key": "MIA",
        "incident_code": "MOCK240501",
        "incident_date": _timestamp(6, 22, 0),
        "incident_offense": "Robbery",
        "incident_offense_code": "120",
        "incident_offense_description": "Robbery - Strong Arm",
        "incident_offense_detail_description": "Street robbery near SW 8th St & SW 17th Ave",
        "incident_offense_crime_against": "Person",
        "incident_offense_action": "C",
        "incident_source_original_type": "ROBBERY - STRONG ARM",
        "incident_source_name": "Mock_Data",
        "incident_latitude": 25.7665,
        "incident_longitude": -80.2204,
        "incident_address": "1700 SW 8th St",
    },
    {
        "city_key": "MIA",
        "incident_code": "MOCK240502",
        "incident_date": _timestamp(7, 1, 10),
        "incident_offense": "Weapon Law Violations",
        "incident_offense_code": "520",
        "incident_offense_description": "Weapons Violation",
        "incident_offense_detail_description": "Illegal firearm near SW 8th St & SW 14th Ave",
        "incident_offense_crime_against": "Society",
        "incident_offense_action": "A",
        "incident_source_original_type": "WEAPONS - CARRYING",
        "incident_source_name": "Mock_Data",
        "incident_latitude": 25.7693,
        "incident_longitude": -80.2137,
        "incident_address": "1400 SW 8th St",
    },
    {
        "city_key": "MIA",
        "incident_code": "MOCK240503",
        "incident_date": _timestamp(8, 4, 20),
        "incident_offense": "Drug/Narcotic Violations",
        "incident_offense_code": "35A",
        "incident_offense_description": "Drug Possession",
        "incident_offense_detail_description": "Narcotics arrest near SW 12th Ave & Flagler St",
        "incident_offense_crime_against": "Society",
        "incident_offense_action": "A",
        "incident_source_original_type": "NARCOTICS - POSSESSION",
        "incident_source_name": "Mock_Data",
        "incident_latitude": 25.7731,
        "incident_longitude": -80.2109,
        "incident_address": "SW 12th Ave & W Flagler St",
    },
    # Edgewater / R6
    {
        "city_key": "MIA",
        "incident_code": "MOCK240601",
        "incident_date": _timestamp(6, 21, 35),
        "incident_offense": "Aggravated Assault",
        "incident_offense_code": "13A",
        "incident_offense_description": "Aggravated Assault",
        "incident_offense_detail_description": "Altercation near NE 27th St & Biscayne Blvd",
        "incident_offense_crime_against": "Person",
        "incident_offense_action": "C",
        "incident_source_original_type": "ASSAULT - AGGRAVATED",
        "incident_source_name": "Mock_Data",
        "incident_latitude": 25.8012,
        "incident_longitude": -80.1880,
        "incident_address": "NE 27th St & Biscayne Blvd",
    },
    {
        "city_key": "MIA",
        "incident_code": "MOCK240602",
        "incident_date": _timestamp(7, 2, 5),
        "incident_offense": "Motor Vehicle Theft",
        "incident_offense_code": "240",
        "incident_offense_description": "Motor Vehicle Theft",
        "incident_offense_detail_description": "Scooter theft near NE 30th St & NE 1st Ave",
        "incident_offense_crime_against": "Property",
        "incident_offense_action": "C",
        "incident_source_original_type": "MOTOR VEHICLE THEFT - SCOOTER",
        "incident_source_name": "Mock_Data",
        "incident_latitude": 25.8053,
        "incident_longitude": -80.1871,
        "incident_address": "NE 30th St & NE 1st Ave",
    },
    {
        "city_key": "MIA",
        "incident_code": "MOCK240603",
        "incident_date": _timestamp(8, 3, 30),
        "incident_offense": "Robbery",
        "incident_offense_code": "120",
        "incident_offense_description": "Robbery",
        "incident_offense_detail_description": "Late-night mugging near Margaret Pace Park",
        "incident_offense_crime_against": "Person",
        "incident_offense_action": "C",
        "incident_source_original_type": "ROBBERY - STRONG ARM",
        "incident_source_name": "Mock_Data",
        "incident_latitude": 25.8015,
        "incident_longitude": -80.1861,
        "incident_address": "1745 N Bayshore Dr",
    },
    # Design District / R7
    {
        "city_key": "MIA",
        "incident_code": "MOCK240701",
        "incident_date": _timestamp(6, 22, 20),
        "incident_offense": "Burglary",
        "incident_offense_code": "220",
        "incident_offense_description": "Commercial Burglary",
        "incident_offense_detail_description": "Boutique break-in near NE 42nd St & NE 2nd Ave",
        "incident_offense_crime_against": "Property",
        "incident_offense_action": "C",
        "incident_source_original_type": "BURGLARY - COMMERCIAL",
        "incident_source_name": "Mock_Data",
        "incident_latitude": 25.8176,
        "incident_longitude": -80.1919,
        "incident_address": "NE 42nd St & NE 2nd Ave",
    },
    {
        "city_key": "MIA",
        "incident_code": "MOCK240702",
        "incident_date": _timestamp(7, 0, 35),
        "incident_offense": "Theft from Vehicle",
        "incident_offense_code": "23F",
        "incident_offense_description": "Theft from Vehicle",
        "incident_offense_detail_description": "Catalytic converter theft near NE 39th St & N Miami Ave",
        "incident_offense_crime_against": "Property",
        "incident_offense_action": "C",
        "incident_source_original_type": "THEFT - FROM MOTOR VEHICLE",
        "incident_source_name": "Mock_Data",
        "incident_latitude": 25.8158,
        "incident_longitude": -80.1912,
        "incident_address": "3818 NE 1st Ave",
    },
    {
        "city_key": "MIA",
        "incident_code": "MOCK240703",
        "incident_date": _timestamp(8, 1, 50),
        "incident_offense": "Aggravated Assault",
        "incident_offense_code": "13A",
        "incident_offense_description": "Aggravated Assault",
        "incident_offense_detail_description": "Knife threat near NE 41st St & NE 1st Ave",
        "incident_offense_crime_against": "Person",
        "incident_offense_action": "C",
        "incident_source_original_type": "ASSAULT - AGGRAVATED",
        "incident_source_name": "Mock_Data",
        "incident_latitude": 25.8179,
        "incident_longitude": -80.1905,
        "incident_address": "41 NE 41st St",
    },
    # Coral Gables / R8
    {
        "city_key": "MIA",
        "incident_code": "MOCK240801",
        "incident_date": _timestamp(6, 21, 10),
        "incident_offense": "Robbery",
        "incident_offense_code": "120",
        "incident_offense_description": "Robbery - Purse Snatch",
        "incident_offense_detail_description": "Purse snatching near Miracle Mile & Ponce de Leon Blvd",
        "incident_offense_crime_against": "Person",
        "incident_offense_action": "C",
        "incident_source_original_type": "ROBBERY - PURSE SNATCH",
        "incident_source_name": "Mock_Data",
        "incident_latitude": 25.7492,
        "incident_longitude": -80.2587,
        "incident_address": "300 Miracle Mile",
    },
    {
        "city_key": "MIA",
        "incident_code": "MOCK240802",
        "incident_date": _timestamp(7, 2, 40),
        "incident_offense": "Burglary",
        "incident_offense_code": "220",
        "incident_offense_description": "Commercial Burglary",
        "incident_offense_detail_description": "Office burglary near Alhambra Cir & Salzedo St",
        "incident_offense_crime_against": "Property",
        "incident_offense_action": "C",
        "incident_source_original_type": "BURGLARY - COMMERCIAL",
        "incident_source_name": "Mock_Data",
        "incident_latitude": 25.7513,
        "incident_longitude": -80.2574,
        "incident_address": "200 Alhambra Cir",
    },
    {
        "city_key": "MIA",
        "incident_code": "MOCK240803",
        "incident_date": _timestamp(8, 3, 5),
        "incident_offense": "Motor Vehicle Theft",
        "incident_offense_code": "240",
        "incident_offense_description": "Motor Vehicle Theft",
        "incident_offense_detail_description": "Parking garage theft near Andalusia Ave",
        "incident_offense_crime_against": "Property",
        "incident_offense_action": "C",
        "incident_source_original_type": "MOTOR VEHICLE THEFT",
        "incident_source_name": "Mock_Data",
        "incident_latitude": 25.7488,
        "incident_longitude": -80.2599,
        "incident_address": "275 Andalusia Ave",
    },
    # Miami Beach / R9
    {
        "city_key": "MIA",
        "incident_code": "MOCK240901",
        "incident_date": _timestamp(6, 23, 10),
        "incident_offense": "Aggravated Assault",
        "incident_offense_code": "13A",
        "incident_offense_description": "Aggravated Assault",
        "incident_offense_detail_description": "Nightclub altercation near Collins Ave & 75th St",
        "incident_offense_crime_against": "Person",
        "incident_offense_action": "C",
        "incident_source_original_type": "ASSAULT - AGGRAVATED",
        "incident_source_name": "Mock_Data",
        "incident_latitude": 25.8443,
        "incident_longitude": -80.1208,
        "incident_address": "7501 Collins Ave",
    },
    {
        "city_key": "MIA",
        "incident_code": "MOCK240902",
        "incident_date": _timestamp(7, 1, 30),
        "incident_offense": "Theft",
        "incident_offense_code": "23H",
        "incident_offense_description": "Other Theft",
        "incident_offense_detail_description": "Beach bag theft near 72nd St & Harding Ave",
        "incident_offense_crime_against": "Property",
        "incident_offense_action": "C",
        "incident_source_original_type": "THEFT - OTHER",
        "incident_source_name": "Mock_Data",
        "incident_latitude": 25.8421,
        "incident_longitude": -80.1203,
        "incident_address": "7201 Harding Ave",
    },
    {
        "city_key": "MIA",
        "incident_code": "MOCK240903",
        "incident_date": _timestamp(8, 4, 40),
        "incident_offense": "Robbery",
        "incident_offense_code": "120",
        "incident_offense_description": "Robbery",
        "incident_offense_detail_description": "Attempted robbery near Collins Ave & 79th St",
        "incident_offense_crime_against": "Person",
        "incident_offense_action": "C",
        "incident_source_original_type": "ROBBERY - STRONG ARM",
        "incident_source_name": "Mock_Data",
        "incident_latitude": 25.8486,
        "incident_longitude": -80.1190,
        "incident_address": "7900 Collins Ave",
    },
    # Doral / R10
    {
        "city_key": "MIA",
        "incident_code": "MOCK241001",
        "incident_date": _timestamp(6, 21, 55),
        "incident_offense": "Burglary",
        "incident_offense_code": "220",
        "incident_offense_description": "Commercial Burglary",
        "incident_offense_detail_description": "Burglary near NW 53rd St & NW 83rd Ave",
        "incident_offense_crime_against": "Property",
        "incident_offense_action": "C",
        "incident_source_original_type": "BURGLARY - COMMERCIAL",
        "incident_source_name": "Mock_Data",
        "incident_latitude": 25.8136,
        "incident_longitude": -80.3581,
        "incident_address": "8300 NW 53rd St",
    },
    {
        "city_key": "MIA",
        "incident_code": "MOCK241002",
        "incident_date": _timestamp(7, 2, 20),
        "incident_offense": "Aggravated Assault",
        "incident_offense_code": "13A",
        "incident_offense_description": "Aggravated Assault",
        "incident_offense_detail_description": "Parking lot argument near NW 41st St & NW 87th Ave",
        "incident_offense_crime_against": "Person",
        "incident_offense_action": "C",
        "incident_source_original_type": "ASSAULT - AGGRAVATED",
        "incident_source_name": "Mock_Data",
        "incident_latitude": 25.8107,
        "incident_longitude": -80.3539,
        "incident_address": "4100 NW 87th Ave",
    },
    {
        "city_key": "MIA",
        "incident_code": "MOCK241003",
        "incident_date": _timestamp(8, 3, 45),
        "incident_offense": "Motor Vehicle Theft",
        "incident_offense_code": "240",
        "incident_offense_description": "Motor Vehicle Theft",
        "incident_offense_detail_description": "Truck theft near NW 36th St & NW 79th Ave",
        "incident_offense_crime_against": "Property",
        "incident_offense_action": "C",
        "incident_source_original_type": "MOTOR VEHICLE THEFT",
        "incident_source_name": "Mock_Data",
        "incident_latitude": 25.8093,
        "incident_longitude": -80.3298,
        "incident_address": "3601 NW 79th Ave",
    },
]


def main() -> None:
    payload = json.loads(DATA_PATH.read_text())
    incidents = payload.get("incidents", [])
    existing_codes = {str(item.get("incident_code")) for item in incidents}
    additions = [item for item in NEW_INCIDENTS if item["incident_code"] not in existing_codes]
    incidents.extend(additions)
    payload["incidents"] = incidents
    payload["incidents_count"] = len(incidents)
    DATA_PATH.write_text(json.dumps(payload, indent=4))
    print(f"Added {len(additions)} incidents. Total now {payload['incidents_count']}.")


if __name__ == "__main__":
    main()
